# Generated by Django 5.0.7 on 2024-08-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_localization'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypost',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='categorypost',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='categorypost',
            name='keywords_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='categorypost',
            name='keywords_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='categorypost',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categorypost',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
